# Generated by Django 2.2.9 on 2022-03-29 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220328_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': ('group',), 'verbose_name_plural': ('groups',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': (['-pub_date'],), 'verbose_name': ('post',), 'verbose_name_plural': ('posts',)},
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='posts.Group', verbose_name='Сообщество'),
        ),
    ]
